### ISSUE TITLE
Programs often disappear

### ISSUE THREAD

**Issue by xli-cube** [subspace/space-acres#177]
I tried using ACRES or CLI, but both encountered this issue.
cpu:i9-14900kf , 32G
this log 
![DL)Q$CAQ8BJ$O7XC6DD0@)9](https://github.com/subspace/space-acres/assets/161856328/587eaa8b-04e4-4669-a104-7eef5bf3a627)
![Y(U5I4MC44E@3W{YTBN%UUK](https://github.com/subspace/space-acres/assets/161856328/605b8e01-eef0-414d-8fb5-694880d99edd)

**Comment by xli-cube** [comment]
[space-acres.zip](https://github.com/subspace/space-acres/files/15011520/space-acres.zip)
this log file.
When the piece is syncing, the interface often appears unresponsive and then disappears.

Intel(R) Core(TM) i9-14900KF   3.20 GHz
RAM	32.0 GB

**Comment by nazar-pc** [comment]
According to screenshots your computer is most likely unstable, see https://forum.subspace.network/t/thread-plotting-1-1-panicked/2404?u=nazar-pc
The first thing to check is RAM (XMP), check forum for details and further discussion.

**Comment by ShaunWuu** [comment]
> According to screenshots your computer is most likely unstable, see https://forum.subspace.network/t/thread-plotting-1-1-panicked/2404?u=nazar-pc The first thing to check is RAM (XMP), check forum for details and further discussion.

@xli-cube is my friend. He checked that XMP is off. And found no condition looks like the one in the forum

**Comment by nazar-pc** [comment]
"overflowed its stack" is one of the indications of unstable hardware. Application shouldn't just exit for no reason. You might be able to find more details in system events in Windows, but you'll likely find some segfaults there that are results of unstable hardware.

Even if XMP is off computer can be unstable, my 13900K is quite unstable sometimes as well, see reports like https://videocardz.com/newz/intel-13th-14th-core-raptor-lake-gaming-instability-is-now-being-investigated and https://videocardz.com/newz/nvidia-recommends-intel-raptor-lake-cpu-users-to-consult-intel-in-case-of-stability-issues.

I don't think there is anything to fix in Space Acres or other Subspace software. Note that plotting in Subspace is memory-intensive and can uncover instability in seemingly stable otherwise system.

**Comment by xli-cube** [comment]
3q

**Comment by xli-cube** [comment]
Thank you

**Comment by xli-cube** [comment]
perfect !! 
The program crash is not related to XMP, CPU frequency reduction has been resolved
